# Generated by Django 6.0.1 on 2026-03-23 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='map_image',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='tokens',
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нова сцена', max_length=100)),
                ('tokens', models.JSONField(default=list)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='maps/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='table.gamesession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='active_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='table.scene'),
        ),
    ]
