# Generated by Django 6.0.1 on 2026-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_remove_gamesession_map_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='grid_color',
            field=models.CharField(default='rgba(255,255,255,0.15)', max_length=30),
        ),
        migrations.AddField(
            model_name='scene',
            name='grid_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='grid_size',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='scene',
            name='grid_snap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='grid_type',
            field=models.CharField(choices=[('square', 'Square'), ('hex', 'Hex')], default='square', max_length=10),
        ),
    ]
