# Generated by Django 6.0.1 on 2026-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_scene_grid_color_scene_grid_enabled_scene_grid_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='grid_color',
            field=models.CharField(default='rgba(255,255,255,0.15)', max_length=30),
        ),
    ]
