# Generated by Django 6.0.1 on 2026-04-17 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0004_alter_scene_grid_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('character', 'Персонаж'), ('location', 'Локація'), ('map', 'Карта'), ('creature', 'Істота'), ('weapon', 'Зброя'), ('item', 'Предмет'), ('faction', 'Фракція'), ('event', 'Подія'), ('other', 'Інше')], default='other', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='worldbuilder/cards/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible_in_wiki', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DnDSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.CharField(blank=True, max_length=100)),
                ('subclass', models.CharField(blank=True, max_length=100)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('background', models.CharField(blank=True, max_length=100)),
                ('alignment', models.CharField(blank=True, max_length=50)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('strength', models.PositiveSmallIntegerField(default=10)),
                ('dexterity', models.PositiveSmallIntegerField(default=10)),
                ('constitution', models.PositiveSmallIntegerField(default=10)),
                ('intelligence', models.PositiveSmallIntegerField(default=10)),
                ('wisdom', models.PositiveSmallIntegerField(default=10)),
                ('charisma', models.PositiveSmallIntegerField(default=10)),
                ('max_hp', models.PositiveSmallIntegerField(default=0)),
                ('current_hp', models.SmallIntegerField(default=0)),
                ('temporary_hp', models.PositiveSmallIntegerField(default=0)),
                ('armor_class', models.PositiveSmallIntegerField(default=10)),
                ('initiative', models.SmallIntegerField(default=0)),
                ('speed', models.PositiveSmallIntegerField(default=30)),
                ('hit_dice', models.CharField(blank=True, max_length=20)),
                ('saving_throws', models.JSONField(blank=True, default=dict)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('equipment', models.TextField(blank=True)),
                ('features_and_traits', models.TextField(blank=True)),
                ('other_proficiencies', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('spellcasting_ability', models.CharField(blank=True, max_length=20)),
                ('spell_save_dc', models.PositiveSmallIntegerField(default=0)),
                ('spell_attack_bonus', models.SmallIntegerField(default=0)),
                ('spells', models.JSONField(blank=True, default=dict)),
                ('personality_traits', models.TextField(blank=True)),
                ('ideals', models.TextField(blank=True)),
                ('bonds', models.TextField(blank=True)),
                ('flaws', models.TextField(blank=True)),
                ('backstory', models.TextField(blank=True)),
                ('card', models.OneToOneField(limit_choices_to={'card_type': 'character'}, on_delete=django.db.models.deletion.CASCADE, related_name='dnd_sheet', to='worldbuilder.card')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='worldbuilder.folder')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='worldbuilder.folder'),
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='worldbuilder/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_settings', to='table.gamesession')),
                ('visible_cards', models.ManyToManyField(blank=True, related_name='wiki_settings', to='worldbuilder.card')),
                ('visible_folders', models.ManyToManyField(blank=True, related_name='wiki_settings', to='worldbuilder.folder')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_settings', to='worldbuilder.world')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='worldbuilder.world'),
        ),
        migrations.AddField(
            model_name='card',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='worldbuilder.world'),
        ),
    ]
