# Generated by Django 6.0.1 on 2026-02-05 13:19

import characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_character_charisma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='wallet',
            field=models.JSONField(default=characters.models.default_wallet),
        ),
    ]
