# Generated by Django 6.0.1 on 2026-02-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_avatar_alter_character_max_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='proficiencies',
            field=models.JSONField(default=list),
        ),
    ]
