# Generated by Django 6.0.1 on 2026-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_proficiencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attacks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
