# Generated by Django 6.0.1 on 2026-03-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_character_attacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attacks_and_spellcasting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='features_and_traits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
