# Generated by Django 6.0.1 on 2026-03-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_character_attacks_and_spellcasting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='attacks_and_spellcasting',
            new_name='attack_notes',
        ),
    ]
