# Generated by Django 6.0.1 on 2026-03-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_rename_attacks_and_spellcasting_character_attack_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='features_and_traits',
            new_name='features_notes',
        ),
    ]
