# Generated by Django 6.0.1 on 2026-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_rename_features_and_traits_character_features_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='creature_size',
            field=models.CharField(blank=True, default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory_capacity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='treasure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
