# Generated by Django 6.0.1 on 2026-03-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_character_creature_size_character_equipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='equipment',
            new_name='inventory',
        ),
    ]
