# Generated by Django 6.0.1 on 2026-03-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_rename_equipment_character_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
