# Generated by Django 6.0.1 on 2026-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_character_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='appearance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='goals',
            field=models.TextField(blank=True, default=''),
        ),
    ]
