# Generated by Django 6.0.1 on 2026-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_character_appearance_character_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='my_spells',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
