# Generated by Django 6.0.1 on 2026-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_character_my_spells'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spell_slots',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
